#!/bin/sh

swift package --allow-writing-to-directory "$PWD/docs" \
    generate-documentation --target PostgresClientORM \
    --disable-indexing \
    --transform-for-static-hosting \
    --hosting-base-path PostgresClientORM \
    --output-path "$PWD/docs"
